## **NumPy First Assignment** 
### **Author: Muhammad Arslan Ifitikhar** 

### Topic: Array Creation
1. **Question.#01** 
   - 1.	Create a numpy array of size 10, filled with zeros.

In [2]:
# import library first
import numpy as np

In [3]:
# creating array of size 10 with value 10 in it.
array_zero = np.zeros(10)
array_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

   - 2.	Create a numpy array with values ranging from 10 to 49 and set its datatype to float.

In [4]:
# an array with value range from 10 to 49 and dtype of float.
array_float = np.arange(10,50,dtype=float)
array_float

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

   - 3.	Create a numpy matrix of 2*2 integers, filled with ones.

In [5]:
# a numpy matrix of 2x2 integers.
matrix_2x2 = np.ones((2,2),dtype=int)
matrix_2x2

array([[1, 1],
       [1, 1]])

   - 4.	Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
# a numpy matrix of 3x2 of float numbers.
matrix_3x2 = np.ones((3,2),dtype=float)
matrix_3x2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

   - 5.	Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones. 

In [7]:
# creating a new array as the shape of already exisiting array. 
X = np.array([1,2,3])
ones_like_X = np.ones_like(X)
ones_like_X

array([1, 1, 1])

- 6.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [8]:
# creating a new matrix as the shape of already exisiting matrix. 
X = np.array([[1,2,3],[4,5,6]])
ones_like_matrix_X = np.zeros_like(X)
ones_like_matrix_X

array([[0, 0, 0],
       [0, 0, 0]])

   - 7.	Create a numpy matrix of 4*4 integers, filled with fives.

In [9]:
# a matrix of 4x4 integers with value 5 in it.
matrix_4x4 = np.full((4,4),5,dtype=int)
matrix_4x4

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

   - 8.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [10]:
# a new matrix with the shape of already given matrix filled with seven.
X = np.array([[1,2,3],[4,5,6]])
matrix_updated = np.full_like(X,7)
matrix_updated

array([[7, 7, 7],
       [7, 7, 7]])

- 9.	Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [12]:
# a identity matrix of shape 3x3.
idt_matrix = np.eye(3)
idt_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- 10.	Create a numpy array, filled with 3 random integer values between 1 and 10.

In [13]:
# a random array between 1 and 10 of 3 random values.
random_array = np.random.randint(1, 10, size=3)
random_array

array([9, 5, 7])

- 11.	Create a 3x3x3 numpy matrix, filled with random float values.

In [14]:
random_matrix = np.random.rand(3,3,3)
random_matrix

array([[[0.34603049, 0.1982701 , 0.91309665],
        [0.23053318, 0.53192553, 0.72050508],
        [0.33154219, 0.43749725, 0.44785959]],

       [[0.65202531, 0.6935184 , 0.95694225],
        [0.92292353, 0.77311951, 0.75634929],
        [0.02453845, 0.13634965, 0.25060282]],

       [[0.7601423 , 0.81008081, 0.4100993 ],
        [0.48679397, 0.8115998 , 0.52386015],
        [0.3974346 , 0.31760924, 0.82505047]]])

- 12.	Create a numpy array with numbers from 1 to 10.

In [18]:
# an array with numbers from 1 to 10.
numpy_array = np.arange(1,11)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- 13.	Create a numpy array with the odd numbers between 1 to 10.

In [19]:
# a numpy array of odd numbers from 1 to 10.
odd_array = np.arange(1,11,2)
odd_array

array([1, 3, 5, 7, 9])

- 14.	Create a numpy array with numbers from 1 to 10, in descending order.

In [20]:
# an array from numbers 1 to 10 in descending order.
desc_array = np.arange(10, 0, -1)
desc_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

- 15.	Create a 3*3 numpy matrix, filled with values ranging from 0 to 8.

In [21]:
# a numpy matrix of 3x3 with value range from 0 to 8.
frist_array = np.arange(9)
filled_matrix = frist_array.reshape(3, 3)
filled_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Topic: Array Indexing
2. **Question.#02**
   - 1.	Given the X numpy array, show its first element.
X = np.array(['A','B','C','D','E']) 

In [23]:
X = np.array(['A','B','C','D','E'])
first_element = X[0]
first_element

'A'

- 2.	Given the X numpy array, show its last element. 
X = np.array(['A','B','C','D','E'])

In [24]:
X = np.array(['A','B','C','D','E'])
last_element = X[-1]
last_element

'E'

3.	Given the X numpy array, show its first three elements. 
X = np.array(['A','B','C','D','E'])


In [25]:
X = np.array(['A','B','C','D','E'])
first_3_elements = X[:3]
first_3_elements

array(['A', 'B', 'C'], dtype='<U1')

- 4.	Given the X numpy array, show all middle elements. 
X = np.array(['A','B','C','D','E'])


In [28]:
X = np.array(['A','B','C','D','E'])
middle_element = len(X)//2
X[middle_element]

'C'

- 5.	Given the X numpy array, show the elements in reverse position. X = np.array(['A','B','C','D','E'])


In [30]:
X = np.array(['A','B','C','D','E'])
reverse_position = X[::-1]
reverse_position

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

- 6.	Given the X numpy array, show the elements in an odd position.
X = np.array(['A','B','C','D','E'])

In [32]:
X = np.array(['A','B','C','D','E'])
odd_position = X[1::2]
odd_position

array(['B', 'D'], dtype='<U1')

- 7.	Given the X numpy matrix, show the first row’s elements.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [36]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
row_first = X[0]
row_first

array([1, 2, 3, 4])

- 8.	Given the X numpy matrix, show the last row elements. 
  
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [37]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
last_row = X[-1]
last_row

array([13, 14, 15, 16])

- 9.	Given the X numpy matrix, show the first element on first row

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [38]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
first_row_first_element = X[0,0]
first_row_first_element

1

- 10.	Given the X numpy matrix, show the last element on last row.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [39]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
last_row_last_element = X[-1,-1]
last_row_last_element

16

- 11.	Given the X numpy matrix, show the first two elements on the first two rows.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [40]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
first_2_rows_2_elements = X[:2,:2]
first_2_rows_2_elements

array([[1, 2],
       [5, 6]])

- 12.	Given the X numpy matrix, show the last two elements on the last two rows

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [43]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
last_2_rows_2_elements = X[-2:,-2:]
last_2_rows_2_elements

array([[11, 12],
       [15, 16]])

### Topic: Array Manipulation
3. **Question.#03**
   - 1.	Convert the given integer numpy array to float (you need to google the function that will help you do this)

X = [-5, -3, 0, 10, 40]

In [49]:
X = np.array([-5, -3, 0, 10, 40])
float_array = X.astype(float)
print(float_array)
float_array.dtype

[-5. -3.  0. 10. 40.]


dtype('float64')

- 2.	Reverse the given numpy array (first element becomes last) through indexing. 
X = [-5, -3, 0, 10, 40]

In [51]:
X = np.array([-5, -3, 0, 10, 40])
reversed_array = X[::-1]
reversed_array

array([40, 10,  0, -3, -5])

- 3.	Given the X numpy array, set the fifth element equal to 1. 
X = np.zeros(10)

In [53]:
X = np.zeros(10)
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

- 4.	Given the X numpy matrix, change the last row with all 1

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [54]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

- 5.	Given the X numpy matrix, add 5 to every element

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [55]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X+=5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])